import { Tea, Note, User } from '../types';

export const currentUser: User = {
  id: 'user-1',
  name: '김차인',
  email: 'tea@example.com',
};

export const mockTeas: Tea[] = [
  {
    id: 'tea-1',
    name: '정산소종',
    year: 2023,
    type: '홍차',
    seller: '차향',
    origin: '중국 푸젠',
    averageRating: 4.5,
    reviewCount: 12,
  },
  {
    id: 'tea-2',
    name: '대홍포',
    year: 2022,
    type: '우롱차',
    seller: '찻잎',
    origin: '중국 우이산',
    averageRating: 4.8,
    reviewCount: 8,
  },
  {
    id: 'tea-3',
    name: '용정',
    year: 2024,
    type: '녹차',
    seller: '차향',
    origin: '중국 항저우',
    averageRating: 4.2,
    reviewCount: 15,
  },
  {
    id: 'tea-4',
    name: '백호은침',
    year: 2023,
    type: '백차',
    seller: '티하우스',
    origin: '중국 푸젠',
    averageRating: 4.6,
    reviewCount: 6,
  },
  {
    id: 'tea-5',
    name: '철관음',
    year: 2023,
    type: '우롱차',
    seller: '찻잎',
    origin: '중국 안시',
    averageRating: 4.4,
    reviewCount: 10,
  },
];

export const mockNotes: Note[] = [
  {
    id: 'note-1',
    teaId: 'tea-1',
    teaName: '정산소종',
    userId: 'user-1',
    userName: '김차인',
    rating: 4.5,
    ratings: {
      richness: 4,
      strength: 3,
      smoothness: 5,
      clarity: 4,
      complexity: 4,
    },
    memo: '은은한 훈향이 매력적입니다. 부드러운 목넘김과 긴 여운이 좋았어요.',
    isPublic: true,
    createdAt: new Date('2024-11-10'),
  },
  {
    id: 'note-2',
    teaId: 'tea-2',
    teaName: '대홍포',
    userId: 'user-2',
    userName: '이다원',
    rating: 5,
    ratings: {
      richness: 5,
      strength: 4,
      smoothness: 4,
      clarity: 5,
      complexity: 5,
    },
    memo: '깊은 향과 복합적인 맛이 인상적입니다. 바위의 기운이 느껴지는 듯한 미네랄리티가 훌륭해요.',
    isPublic: true,
    createdAt: new Date('2024-11-09'),
  },
  {
    id: 'note-3',
    teaId: 'tea-3',
    teaName: '용정',
    userId: 'user-3',
    userName: '박녹차',
    rating: 4,
    ratings: {
      richness: 3,
      strength: 2,
      smoothness: 5,
      clarity: 5,
      complexity: 3,
    },
    memo: '깨끗하고 상쾌한 맛. 봄의 신선함이 그대로 전해집니다.',
    isPublic: true,
    createdAt: new Date('2024-11-08'),
  },
  {
    id: 'note-4',
    teaId: 'tea-1',
    teaName: '정산소종',
    userId: 'user-1',
    userName: '김차인',
    rating: 4,
    ratings: {
      richness: 4,
      strength: 3,
      smoothness: 4,
      clarity: 4,
      complexity: 3,
    },
    memo: '개인 기록용 메모입니다.',
    isPublic: false,
    createdAt: new Date('2024-11-07'),
  },
  {
    id: 'note-5',
    teaId: 'tea-4',
    teaName: '백호은침',
    userId: 'user-4',
    userName: '최은침',
    rating: 4.8,
    ratings: {
      richness: 4,
      strength: 2,
      smoothness: 5,
      clarity: 5,
      complexity: 4,
    },
    memo: '섬세하고 우아한 맛. 은은한 꽃향기와 달콤함이 조화롭습니다.',
    isPublic: true,
    createdAt: new Date('2024-11-06'),
  },
];
