import { MigrationInterface, QueryRunner } from "typeorm";

export class AddProfileImageUrlToUsers1765282420978 implements MigrationInterface {
    name = 'AddProfileImageUrlToUsers1765282420978'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_authentications\` DROP FOREIGN KEY \`user_authentications_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`note_tags\` DROP FOREIGN KEY \`note_tags_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`note_tags\` DROP FOREIGN KEY \`note_tags_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`note_axis_value\` DROP FOREIGN KEY \`note_axis_value_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`note_axis_value\` DROP FOREIGN KEY \`note_axis_value_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`rating_axis\` DROP FOREIGN KEY \`rating_axis_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`notes\` DROP FOREIGN KEY \`FK_notes_rating_schema\``);
        await queryRunner.query(`ALTER TABLE \`notes\` DROP FOREIGN KEY \`FK_notes_tea\``);
        await queryRunner.query(`ALTER TABLE \`notes\` DROP FOREIGN KEY \`FK_notes_user\``);
        await queryRunner.query(`ALTER TABLE \`note_likes\` DROP FOREIGN KEY \`note_likes_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`note_likes\` DROP FOREIGN KEY \`note_likes_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`note_bookmarks\` DROP FOREIGN KEY \`note_bookmarks_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`note_bookmarks\` DROP FOREIGN KEY \`note_bookmarks_ibfk_2\``);
        await queryRunner.query(`DROP INDEX \`UNIQUE_provider_providerId\` ON \`user_authentications\``);
        await queryRunner.query(`DROP INDEX \`IDX_user_authentications_userId\` ON \`user_authentications\``);
        await queryRunner.query(`DROP INDEX \`IDX_user_authentications_provider\` ON \`user_authentications\``);
        await queryRunner.query(`DROP INDEX \`name\` ON \`tags\``);
        await queryRunner.query(`DROP INDEX \`idx_name\` ON \`tags\``);
        await queryRunner.query(`DROP INDEX \`unique_note_tag\` ON \`note_tags\``);
        await queryRunner.query(`DROP INDEX \`idx_noteId\` ON \`note_tags\``);
        await queryRunner.query(`DROP INDEX \`idx_tagId\` ON \`note_tags\``);
        await queryRunner.query(`DROP INDEX \`unique_note_axis\` ON \`note_axis_value\``);
        await queryRunner.query(`DROP INDEX \`IDX_note_axis_value_axisId\` ON \`note_axis_value\``);
        await queryRunner.query(`DROP INDEX \`IDX_note_axis_value_axis_value\` ON \`note_axis_value\``);
        await queryRunner.query(`DROP INDEX \`IDX_rating_axis_schemaId\` ON \`rating_axis\``);
        await queryRunner.query(`DROP INDEX \`IDX_rating_axis_code\` ON \`rating_axis\``);
        await queryRunner.query(`DROP INDEX \`IDX_rating_schema_code_version\` ON \`rating_schema\``);
        await queryRunner.query(`DROP INDEX \`IDX_rating_schema_isActive\` ON \`rating_schema\``);
        await queryRunner.query(`DROP INDEX \`new_id\` ON \`notes\``);
        await queryRunner.query(`DROP INDEX \`IDX_notes_isPublic\` ON \`notes\``);
        await queryRunner.query(`DROP INDEX \`IDX_notes_createdAt\` ON \`notes\``);
        await queryRunner.query(`DROP INDEX \`IDX_notes_teaId\` ON \`notes\``);
        await queryRunner.query(`DROP INDEX \`IDX_notes_userId\` ON \`notes\``);
        await queryRunner.query(`DROP INDEX \`IDX_notes_schemaId\` ON \`notes\``);
        await queryRunner.query(`DROP INDEX \`new_id\` ON \`teas\``);
        await queryRunner.query(`DROP INDEX \`IDX_teas_name\` ON \`teas\``);
        await queryRunner.query(`DROP INDEX \`IDX_teas_type\` ON \`teas\``);
        await queryRunner.query(`DROP INDEX \`unique_note_user\` ON \`note_likes\``);
        await queryRunner.query(`DROP INDEX \`IDX_note_likes_noteId\` ON \`note_likes\``);
        await queryRunner.query(`DROP INDEX \`IDX_note_likes_userId\` ON \`note_likes\``);
        await queryRunner.query(`DROP INDEX \`unique_note_user_bookmark\` ON \`note_bookmarks\``);
        await queryRunner.query(`DROP INDEX \`IDX_note_bookmarks_noteId\` ON \`note_bookmarks\``);
        await queryRunner.query(`DROP INDEX \`IDX_note_bookmarks_userId\` ON \`note_bookmarks\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`profileImageUrl\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_authentications\` CHANGE \`credential\` \`credential\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_authentications\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user_authentications\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tags\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tags\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`note_tags\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`note_axis_value\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`note_axis_value\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`rating_axis\` CHANGE \`descriptionKo\` \`descriptionKo\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`rating_axis\` CHANGE \`descriptionEn\` \`descriptionEn\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`rating_axis\` CHANGE \`teaType\` \`teaType\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`rating_axis\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`rating_axis\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`rating_schema\` CHANGE \`descriptionKo\` \`descriptionKo\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`rating_schema\` CHANGE \`descriptionEn\` \`descriptionEn\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`rating_schema\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`rating_schema\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`notes\` CHANGE \`overallRating\` \`overallRating\` decimal(3,1) NULL`);
        await queryRunner.query(`ALTER TABLE \`notes\` CHANGE \`memo\` \`memo\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`notes\` DROP COLUMN \`images\``);
        await queryRunner.query(`ALTER TABLE \`notes\` ADD \`images\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`notes\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`notes\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`teas\` CHANGE \`year\` \`year\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`teas\` CHANGE \`seller\` \`seller\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`teas\` CHANGE \`origin\` \`origin\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`teas\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`teas\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`note_likes\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`note_bookmarks\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`CREATE INDEX \`IDX_39490b22fdf310ad4d45593c41\` ON \`user_authentications\` (\`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_b453cba486c3bdf31046376d9c\` ON \`user_authentications\` (\`provider\`, \`providerId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_d90243459a697eadb8ad56e909\` ON \`tags\` (\`name\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_a024216ede3dd087f4900ac8c2\` ON \`note_tags\` (\`tagId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_5d7069f9ad31c7ff1a85311b64\` ON \`note_tags\` (\`noteId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_1c5b938665506d2382bddbbe47\` ON \`note_tags\` (\`noteId\`, \`tagId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_0069aefbf7c4bf8075394435f4\` ON \`note_axis_value\` (\`axisId\`, \`valueNumeric\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_94a04d9f1657f29efbbbd65f88\` ON \`note_axis_value\` (\`axisId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_11fc77a23a61107ac66b280174\` ON \`note_axis_value\` (\`noteId\`, \`axisId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_ebb05710d62b2bff1c7b7370bc\` ON \`note_likes\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_96b8de926816a87a054a0f089f\` ON \`note_likes\` (\`noteId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_b9fd6ca5e42e4911ad6b391d2d\` ON \`note_likes\` (\`noteId\`, \`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_4301907fc8edc9e178f189d2c1\` ON \`note_bookmarks\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_fc02dc079c808a0da4989ff9d2\` ON \`note_bookmarks\` (\`noteId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_4dd9bed29552862e706735f120\` ON \`note_bookmarks\` (\`noteId\`, \`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`user_authentications\` ADD CONSTRAINT \`FK_39490b22fdf310ad4d45593c410\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`note_tags\` ADD CONSTRAINT \`FK_5d7069f9ad31c7ff1a85311b64b\` FOREIGN KEY (\`noteId\`) REFERENCES \`notes\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`note_tags\` ADD CONSTRAINT \`FK_a024216ede3dd087f4900ac8c2f\` FOREIGN KEY (\`tagId\`) REFERENCES \`tags\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`note_axis_value\` ADD CONSTRAINT \`FK_1805cc634ad07e1220b606a3f2d\` FOREIGN KEY (\`noteId\`) REFERENCES \`notes\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`note_axis_value\` ADD CONSTRAINT \`FK_94a04d9f1657f29efbbbd65f881\` FOREIGN KEY (\`axisId\`) REFERENCES \`rating_axis\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rating_axis\` ADD CONSTRAINT \`FK_dda84ccfe8faeb92a50b6709487\` FOREIGN KEY (\`schemaId\`) REFERENCES \`rating_schema\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notes\` ADD CONSTRAINT \`FK_c2c78748c09469410b7941d9bc2\` FOREIGN KEY (\`teaId\`) REFERENCES \`teas\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notes\` ADD CONSTRAINT \`FK_829532ff766505ad7c71592c6a5\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notes\` ADD CONSTRAINT \`FK_6404ee9436aa625c6e850cb1f1d\` FOREIGN KEY (\`schemaId\`) REFERENCES \`rating_schema\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`note_likes\` ADD CONSTRAINT \`FK_96b8de926816a87a054a0f089ff\` FOREIGN KEY (\`noteId\`) REFERENCES \`notes\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`note_likes\` ADD CONSTRAINT \`FK_ebb05710d62b2bff1c7b7370bc6\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`note_bookmarks\` ADD CONSTRAINT \`FK_fc02dc079c808a0da4989ff9d2e\` FOREIGN KEY (\`noteId\`) REFERENCES \`notes\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`note_bookmarks\` ADD CONSTRAINT \`FK_4301907fc8edc9e178f189d2c1a\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`note_bookmarks\` DROP FOREIGN KEY \`FK_4301907fc8edc9e178f189d2c1a\``);
        await queryRunner.query(`ALTER TABLE \`note_bookmarks\` DROP FOREIGN KEY \`FK_fc02dc079c808a0da4989ff9d2e\``);
        await queryRunner.query(`ALTER TABLE \`note_likes\` DROP FOREIGN KEY \`FK_ebb05710d62b2bff1c7b7370bc6\``);
        await queryRunner.query(`ALTER TABLE \`note_likes\` DROP FOREIGN KEY \`FK_96b8de926816a87a054a0f089ff\``);
        await queryRunner.query(`ALTER TABLE \`notes\` DROP FOREIGN KEY \`FK_6404ee9436aa625c6e850cb1f1d\``);
        await queryRunner.query(`ALTER TABLE \`notes\` DROP FOREIGN KEY \`FK_829532ff766505ad7c71592c6a5\``);
        await queryRunner.query(`ALTER TABLE \`notes\` DROP FOREIGN KEY \`FK_c2c78748c09469410b7941d9bc2\``);
        await queryRunner.query(`ALTER TABLE \`rating_axis\` DROP FOREIGN KEY \`FK_dda84ccfe8faeb92a50b6709487\``);
        await queryRunner.query(`ALTER TABLE \`note_axis_value\` DROP FOREIGN KEY \`FK_94a04d9f1657f29efbbbd65f881\``);
        await queryRunner.query(`ALTER TABLE \`note_axis_value\` DROP FOREIGN KEY \`FK_1805cc634ad07e1220b606a3f2d\``);
        await queryRunner.query(`ALTER TABLE \`note_tags\` DROP FOREIGN KEY \`FK_a024216ede3dd087f4900ac8c2f\``);
        await queryRunner.query(`ALTER TABLE \`note_tags\` DROP FOREIGN KEY \`FK_5d7069f9ad31c7ff1a85311b64b\``);
        await queryRunner.query(`ALTER TABLE \`user_authentications\` DROP FOREIGN KEY \`FK_39490b22fdf310ad4d45593c410\``);
        await queryRunner.query(`DROP INDEX \`IDX_4dd9bed29552862e706735f120\` ON \`note_bookmarks\``);
        await queryRunner.query(`DROP INDEX \`IDX_fc02dc079c808a0da4989ff9d2\` ON \`note_bookmarks\``);
        await queryRunner.query(`DROP INDEX \`IDX_4301907fc8edc9e178f189d2c1\` ON \`note_bookmarks\``);
        await queryRunner.query(`DROP INDEX \`IDX_b9fd6ca5e42e4911ad6b391d2d\` ON \`note_likes\``);
        await queryRunner.query(`DROP INDEX \`IDX_96b8de926816a87a054a0f089f\` ON \`note_likes\``);
        await queryRunner.query(`DROP INDEX \`IDX_ebb05710d62b2bff1c7b7370bc\` ON \`note_likes\``);
        await queryRunner.query(`DROP INDEX \`IDX_11fc77a23a61107ac66b280174\` ON \`note_axis_value\``);
        await queryRunner.query(`DROP INDEX \`IDX_94a04d9f1657f29efbbbd65f88\` ON \`note_axis_value\``);
        await queryRunner.query(`DROP INDEX \`IDX_0069aefbf7c4bf8075394435f4\` ON \`note_axis_value\``);
        await queryRunner.query(`DROP INDEX \`IDX_1c5b938665506d2382bddbbe47\` ON \`note_tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_5d7069f9ad31c7ff1a85311b64\` ON \`note_tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_a024216ede3dd087f4900ac8c2\` ON \`note_tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_d90243459a697eadb8ad56e909\` ON \`tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_b453cba486c3bdf31046376d9c\` ON \`user_authentications\``);
        await queryRunner.query(`DROP INDEX \`IDX_39490b22fdf310ad4d45593c41\` ON \`user_authentications\``);
        await queryRunner.query(`ALTER TABLE \`note_bookmarks\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`note_likes\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`teas\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`teas\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`teas\` CHANGE \`origin\` \`origin\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`teas\` CHANGE \`seller\` \`seller\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`teas\` CHANGE \`year\` \`year\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notes\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`notes\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`notes\` DROP COLUMN \`images\``);
        await queryRunner.query(`ALTER TABLE \`notes\` ADD \`images\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notes\` CHANGE \`memo\` \`memo\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notes\` CHANGE \`overallRating\` \`overallRating\` decimal(3,1) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rating_schema\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`rating_schema\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`rating_schema\` CHANGE \`descriptionEn\` \`descriptionEn\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rating_schema\` CHANGE \`descriptionKo\` \`descriptionKo\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rating_axis\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`rating_axis\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`rating_axis\` CHANGE \`teaType\` \`teaType\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rating_axis\` CHANGE \`descriptionEn\` \`descriptionEn\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rating_axis\` CHANGE \`descriptionKo\` \`descriptionKo\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`note_axis_value\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`note_axis_value\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`note_tags\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`tags\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`tags\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`user_authentications\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`user_authentications\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`user_authentications\` CHANGE \`credential\` \`credential\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`profileImageUrl\``);
        await queryRunner.query(`CREATE INDEX \`IDX_note_bookmarks_userId\` ON \`note_bookmarks\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_note_bookmarks_noteId\` ON \`note_bookmarks\` (\`noteId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_note_user_bookmark\` ON \`note_bookmarks\` (\`noteId\`, \`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_note_likes_userId\` ON \`note_likes\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_note_likes_noteId\` ON \`note_likes\` (\`noteId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_note_user\` ON \`note_likes\` (\`noteId\`, \`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_teas_type\` ON \`teas\` (\`type\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_teas_name\` ON \`teas\` (\`name\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`new_id\` ON \`teas\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_notes_schemaId\` ON \`notes\` (\`schemaId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_notes_userId\` ON \`notes\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_notes_teaId\` ON \`notes\` (\`teaId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_notes_createdAt\` ON \`notes\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_notes_isPublic\` ON \`notes\` (\`isPublic\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`new_id\` ON \`notes\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_rating_schema_isActive\` ON \`rating_schema\` (\`isActive\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_rating_schema_code_version\` ON \`rating_schema\` (\`code\`, \`version\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_rating_axis_code\` ON \`rating_axis\` (\`code\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_rating_axis_schemaId\` ON \`rating_axis\` (\`schemaId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_note_axis_value_axis_value\` ON \`note_axis_value\` (\`axisId\`, \`valueNumeric\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_note_axis_value_axisId\` ON \`note_axis_value\` (\`axisId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_note_axis\` ON \`note_axis_value\` (\`noteId\`, \`axisId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_tagId\` ON \`note_tags\` (\`tagId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_noteId\` ON \`note_tags\` (\`noteId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_note_tag\` ON \`note_tags\` (\`noteId\`, \`tagId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_name\` ON \`tags\` (\`name\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`name\` ON \`tags\` (\`name\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_user_authentications_provider\` ON \`user_authentications\` (\`provider\`, \`providerId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_user_authentications_userId\` ON \`user_authentications\` (\`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UNIQUE_provider_providerId\` ON \`user_authentications\` (\`provider\`, \`providerId\`)`);
        await queryRunner.query(`ALTER TABLE \`note_bookmarks\` ADD CONSTRAINT \`note_bookmarks_ibfk_2\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`note_bookmarks\` ADD CONSTRAINT \`note_bookmarks_ibfk_1\` FOREIGN KEY (\`noteId\`) REFERENCES \`notes\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`note_likes\` ADD CONSTRAINT \`note_likes_ibfk_2\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`note_likes\` ADD CONSTRAINT \`note_likes_ibfk_1\` FOREIGN KEY (\`noteId\`) REFERENCES \`notes\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`notes\` ADD CONSTRAINT \`FK_notes_user\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`notes\` ADD CONSTRAINT \`FK_notes_tea\` FOREIGN KEY (\`teaId\`) REFERENCES \`teas\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`notes\` ADD CONSTRAINT \`FK_notes_rating_schema\` FOREIGN KEY (\`schemaId\`) REFERENCES \`rating_schema\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`rating_axis\` ADD CONSTRAINT \`rating_axis_ibfk_1\` FOREIGN KEY (\`schemaId\`) REFERENCES \`rating_schema\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`note_axis_value\` ADD CONSTRAINT \`note_axis_value_ibfk_2\` FOREIGN KEY (\`axisId\`) REFERENCES \`rating_axis\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`note_axis_value\` ADD CONSTRAINT \`note_axis_value_ibfk_1\` FOREIGN KEY (\`noteId\`) REFERENCES \`notes\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`note_tags\` ADD CONSTRAINT \`note_tags_ibfk_2\` FOREIGN KEY (\`tagId\`) REFERENCES \`tags\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`note_tags\` ADD CONSTRAINT \`note_tags_ibfk_1\` FOREIGN KEY (\`noteId\`) REFERENCES \`notes\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`user_authentications\` ADD CONSTRAINT \`user_authentications_ibfk_1\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
    }

}
