export const VALIDATION = {
  NOTE_MEMO_MAX: 5000,
  NOTE_APPEARANCE_MAX: 500,
  NOTE_AROMA_MAX: 500,
  TEA_NAME_MAX: 100,
  TEA_DESCRIPTION_MAX: 1000,
  IMAGE_MAX_COUNT: 5,
  TAG_MAX_COUNT: 10,
  PAGE_MAX_LIMIT: 100,
} as const;
