/// <reference path="../../../types/deno-shim.d.ts" />

/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* 테이블 스키마:
CREATE TABLE kv_store_860b2c16 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// 관리 화면: https://supabase.com/dashboard/project/wsloddppjcclkykjdicl/database/tables

// 이 파일은 Figma Make 데이터를 저장하기 위한 간단한 키-값 인터페이스를 제공합니다. 대부분의 소규모 사용 사례에 충분합니다.
import { createClient } from "npm:@supabase/supabase-js@2.49.8";

const client = () => {
  const supabaseUrl = Deno.env.get("SUPABASE_URL");
  const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

  if (!supabaseUrl || !serviceRoleKey) {
    throw new Error("Missing Supabase credentials");
  }

  return createClient(supabaseUrl, serviceRoleKey);
};

// Set: 키-값 쌍을 데이터베이스에 저장합니다.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_860b2c16").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get: 데이터베이스에서 키-값 쌍을 조회합니다.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_860b2c16").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete: 데이터베이스에서 키-값 쌍을 삭제합니다.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_860b2c16").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Mset: 여러 키-값 쌍을 한 번에 저장합니다.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_860b2c16").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Mget: 여러 키-값 쌍을 한 번에 조회합니다.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_860b2c16").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Mdel: 여러 키-값 쌍을 한 번에 삭제합니다.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_860b2c16").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// GetByPrefix: 특정 접두사로 시작하는 키-값 쌍을 검색합니다.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_860b2c16").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};